### ISSUE TITLE
Error when previous declared is-hidden css rule

### ISSUE THREAD

**Issue by erwanpoupard** [stuartjnelson/badger-accordion#6] opened 2018-03-30 14:40 UTC
Hello, 
There is an error when is-hidden class is already definied in css : 

example : 
https://codepen.io/erwanpoupard/pen/OvvvgL

The accordion doesnt work anymore.

**Comment by stuartjnelson** [comment] 2018-03-30 16:26
Hi @erwanpoupard,

Thanks for getting in touch. Firstly please could I ask if you could give me some more information by filling in the issue template. What are you trying to archive by using this css;

```
.is-hidden {
    display:none !important;
}
```

Since you have set `display: none` for the `is-hidden` selector all it's children of an element with the `is-hidden` selector also now have no visibility and therefore cannot have their height calculated. See the [MDN docs on display](https://developer.mozilla.org/en-US/docs/Web/CSS/display). If you see my two screenshots of where I have you selector being used and then it commented out you'll notice that the inline style of `max-height` when your selector is being used it `max-height: 0px`. The fact the panel isn't opening is expected behaviour

![screen shot 2018-03-30 at 09 20 50](https://user-images.githubusercontent.com/5795894/38145044-53663ff6-33fc-11e8-81d2-0eb513b1f733.png)
![screen shot 2018-03-30 at 09 21 09](https://user-images.githubusercontent.com/5795894/38145046-53c83f12-33fc-11e8-8ea9-0890e0ab4ed5.png)


Do you want to be able to open the accordion panels but without using the headers? Let me know and I'll see if I can help. I'm going to close the issue as its expected behaviour but please do reply on here and I'll see if I can help. 



# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Browser/s & version/s:
* NPM version:
* Node version:

## Failure Logs

Please include any relevant log snippets or files here.

**Closed by stuartjnelson** 2018-03-30 16:26 UTC

**Comment by erwanpoupard** [comment] 2018-04-03 08:07
This rule is just within css foundation framework ;)

**Comment by stuartjnelson** [comment] 2018-04-04 01:18
I see! Well all the classes used in my example are the defaults - [Badger Accordion Options](https://github.com/stuartjnelson/badger-accordion#options). You can override them like this;

```
new BadgerAccordion('.js-badger-accordion', {
    hidenClass: 'erwan-hidden-class`
});
```

Next time I run an update I will change the default to `-is-hidden` to avoid this issue in the future. Thanks for letting me know about the issue with foundation!

**Comment by stuartjnelson** [comment] 2018-04-04 23:37
Hey @erwanpoupard,

I have updated the default class so that it is now `-ba-is-hidden`. I also corrected my spelling mistake for the name of the option. Now if you want to updated the class you would spell hidden correctly (not with a single _n_ as before);

 new BadgerAccordion('.js-badger-accordion', {
    hiddenClass: 'erwan-hidden-class`
});

**Comment by evandiamond** [comment] 2019-02-08 03:48
@erwanpoupard I'm using `"badger-accordion": "^1.2.0"` and still need to use `hidenClass` (spelled incorrectly) for this option to work. :(
