### ISSUE TITLE
Update babel dependencies

### ISSUE THREAD

**Issue by mike3run** [stuartjnelson/badger-accordion#4] opened 2018-03-21 19:03 UTC
Maybe babel could be updated to the latest package `@babel/preset-env` as well as the object assign, since on newer babel configs the build will fail unless you install babel-preset-env and babel-plugin-transform-object-assign

Even the already compiled dist version asks for it 🤷‍♂️  so maybe is not that compiled already 🤔

**Comment by mike3run** [comment] 2018-03-21 19:04
<img width="1586" alt="screen shot 2018-03-21 at 1 04 18 pm" src="https://user-images.githubusercontent.com/7088511/37731652-613f7480-2d08-11e8-839d-57740c98b1cb.png">
<img width="1528" alt="screen shot 2018-03-21 at 1 04 36 pm" src="https://user-images.githubusercontent.com/7088511/37731678-6cb624d0-2d08-11e8-9116-1367120c3b07.png">

**Comment by stuartjnelson** [comment] 2018-03-21 20:18
Hi @mike3run,

Thanks for the info and screenshots. For this ticket could you provide me with some more information? I have an issue ticket template, would you mind filling it out.


# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Browser/s & version/s:
* NPM version:
* Node version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by mike3run** [comment] 2018-03-22 00:47
Of course: I have a repo setup in that exact time when I kind of got this to work before I gave up and contacted you via here:

https://github.com/jeualvarez/RT/tree/a65cb9ab60830f8db1da58cdf8277dc511f7e283

# Steps to reproduce

```js
import BadgerAccordion from 'badger-accordion'

new BadgerAccordion('.js-badger-accordion')
```

And webpack with this config:

https://github.com/jeualvarez/RT/blob/a65cb9ab60830f8db1da58cdf8277dc511f7e283/webpack.config.js

Webpack 4.1.1 with Babel loader 8.0.0-beta.2 with this babel preset:

https://github.com/Pixel2HTML/babel-preset/blob/master/index.js

Relevant babel-loader config with that loader:
https://github.com/jeualvarez/RT/blob/a65cb9ab60830f8db1da58cdf8277dc511f7e283/webpack.config.js#L64-L73

# Context:
<img width="987" alt="screen shot 2018-03-21 at 6 42 56 pm" src="https://user-images.githubusercontent.com/7088511/37744952-b27b7e32-2d37-11e8-9fc2-28311d5f55e3.png">

# Failure Logs
The ones posted above

**Comment by mike3run** [comment] 2018-03-22 00:48
In the end I ended doing a simple accordion as well (not as accessible as yours) but in few lines of code working in IE11

<img width="1920" alt="screen shot 2018-03-21 at 6 39 46 pm" src="https://user-images.githubusercontent.com/7088511/37745078-8150e49a-2d38-11e8-8a49-b286323f8f4b.png">

**Comment by mike3run** [comment] 2018-03-22 00:53
<img width="676" alt="screen shot 2018-03-21 at 6 52 39 pm" src="https://user-images.githubusercontent.com/7088511/37745182-0f805b6a-2d39-11e8-9b70-215b7738639f.png">

**Comment by stuartjnelson** [comment] 2018-03-22 22:55
Hi @mike3run,

Thanks for raising this ticket. I have now updated the `.babelrc` file as well as all Bable dependencies. I cloned your project and got Badger Accordion working with it no problem. Would you mind confirming with me that it works for you with your setup? I appreciate you've removed Badger Accordion as a dependency but it would be great to have confirmation it would now work for you if you decided to use it.

Thanks for your help reporting these bugs.
Stuart

![screen shot 2018-03-22 at 15 48 51](https://user-images.githubusercontent.com/5795894/37802869-6d9289de-2de9-11e8-9d3c-986ed180b0c3.png)

**Comment by stuartjnelson** [comment] 2018-03-24 17:51
Hi @mike3run ,

I'm going to close this issue. If it's still occurring for you please let me know. 

Thanks for your help,
Stuart

**Closed by stuartjnelson** 2018-03-24 17:52 UTC

**Comment by mike3run** [comment] 2018-03-26 15:56
hey there @stuartjnelson thanks a lot for the super quick reply, indeed everything works now, i'll test it again in a more simple way and get back to you with more insights!

**Comment by stuartjnelson** [comment] 2018-03-26 18:57
Hurray! Thanks, @mike3run that would be great. Out of interest are you going to use Badger Accordion on your project or stick with the one you made? I'm wanting to start a showcase of projects that use the accordion and it would be cool if I could include your Render Token project.

**Comment by mike3run** [comment] 2018-03-26 19:09
For the time being I'll continue using the one I made since I have to deliver it by tomorrow haha, but I might get back to it on the weekend and add badger again properly.
